### ISSUE TITLE
Would be great if it's possible to manually select/specifiy the version of downloaded apk and run decompile separately

### ISSUE THREAD

**Issue by Acsimagoria** [fiseleo/BlueArchiveDownloaderJP#1]
I am requesting this because sometimes (i. e. today) the version info fetched from Yostar prod may not match up with available versions from APKPure, which would cause the program to request download of an unavailable version endlessly. If we can specify what version to be downloaded, or just specify the apk that would participate the later steps, it should be more convenient to work around the above loop.

**Comment by fiseleo** [comment]
Thanks for the feedback. I thought no one looked at this project. This is not a problem with apkpure. Today, the official gave the wrong version. I will download the local APK in the future (only look at the APK version, you need to prepare your own APK) to decrypt the game. Data will be added in the future (using C#).

**Comment by Acsimagoria** [comment]
> Thanks for the feedback. I thought no one looked at this project. This is not a problem with apkpure. Today, the official gave the wrong version. I will download the local APK in the future (only look at the APK version, you need to prepare your own APK) to decrypt the game. Data will be added in the future (using C#).

Yeah, that’s exactly what I meant, the json file from Yostar prod referenced in the program (or whatever process that generates “onlineversion.txt”) seems to have an outdated wrong version name. I tried to force “download_asset.py” to download the correct version but it seems that as long as versions from those two txt files aren’t matching each other, the execution would just be trapped into an endless downloading loop. Just never really figured out which file sourced and generated the version from the online json file…

**Comment by fiseleo** [comment]
The temporary fix now is to modify APKversion.txt to 1.46.285252 and then the download source will be changed to Qoo

**Comment by fiseleo** [comment]
I already know the problem is there, it's time for me to fix it

**Comment by Acsimagoria** [comment]
Just wondering if the issue is resolved so far, since changing APKversion.txt to 1.46.285252 didn’t really work out, and the version detect is still recognizing 1.46.285252 as the latest version. Is it possible that Yostar actually changed the url that contains the latest version info, and left anything before 1.46.285252 onto the link referenced in url.py?

**Comment by fiseleo** [comment]
There is no time to fix it recently. Yostar has not changed the url. url.py is the version number obtained by Yostar and added to the suffix of the Apkpure website. Apkpure does not have the 1.46.285252 version number (that is, it cannot be downloaded). 1.46.285252 is iOS. Blue Archive version code.

**Comment by fiseleo** [comment]
![image](https://github.com/fiseleo/BlueArchiveDownloaderJP/assets/123489414/9b6119bc-1859-4f9d-9a45-b185371d7eb0)

**Comment by Acsimagoria** [comment]
Suddenly makes so much sense…

**Comment by Acsimagoria** [comment]
Well if the version tracking cannot be fixed now, are there any suggestions on how I can decrypt the apk if I manually download that already? Which part of the script should I edit to make this happen? (Or in short, a black box that I can input apk address and get decrypted files outputted in the same manner as normal outputs)

**Comment by fiseleo** [comment]
fixed
