### ISSUE TITLE
Opening BAdownload.exe does nothing

### ISSUE THREAD

**Issue by icceytechi** [fiseleo/BlueArchiveDownloaderJP#2]
Sorry I'm new to all of this, I'm not sure what I'm doing wrong

**Comment by fiseleo** [comment]
Is there any error code?

**Comment by icceytechi** [comment]
The CMD flashes for a second and then disappears without any error code/message. I can't even see any text when it flashes.

Maybe I'm missing a prerequisite program?

**Comment by fiseleo** [comment]
What hardware and system? You can try installing .Net8.0 first

**Comment by icceytechi** [comment]
Windows 10. 7800x3D. Nvidia 4080.

And yeah I did after posting that last message, no dice.

**Comment by fiseleo** [comment]
![image](https://github.com/user-attachments/assets/286feaa9-7892-4bd8-a9ca-5ca1c05538e9)
Are you stuck on a screen?

**Comment by icceytechi** [comment]
![Untitled](https://github.com/user-attachments/assets/3f553b0a-737b-48a3-92b9-3b601a69184f)

CMD just flashes, but manually pathing to the exe shows this.

**Comment by fiseleo** [comment]
The python folder in the compressed file must also be unzipped.

**Comment by icceytechi** [comment]
Huh, I'm not familiar with these extensions, how do I do it?

**Comment by fiseleo** [comment]
![image](https://github.com/user-attachments/assets/79795804-fc6b-44b9-97f4-fa7c7d0f9b42)
Decompress it normally and you should have it. Download it again.

**Comment by icceytechi** [comment]
Oh wow

But it seems like the files aren't there 
![test](https://github.com/user-attachments/assets/145fca38-87da-4ad2-8d8d-528b4c4d74b2)

**Comment by fiseleo** [comment]
There is the source code, you should download it from Release

**Comment by icceytechi** [comment]
![test1](https://github.com/user-attachments/assets/68e4c930-a0fb-4dc0-9629-7a6489146a0d)
Almost there I think

**Comment by fiseleo** [comment]
Please see the first issue
https://github.com/fiseleo/BlueArchiveDownloaderJP/issues/1

**Comment by fiseleo** [comment]
fixed
